### ISSUE TITLE
[BUG]- VerifyAuthentication not working as expected

### ISSUE THREAD

**Issue by davappler** [passwordless-id/webauthn#28]
When I call the `verifyAuthentication` function with the given parameters, it does not work as expected.

```
server.verifyAuthentication(
    resp,
    credentialKey,
    expected
  );
```

It displays an error => `An error occurred: crypto is not defined`.

Can anyone help me solve this issue?

I am guessing there is a missing dependency injection somewhere in the codebase.

**Comment by dagnelies** [comment]
Hi. As stated in the readme, Node 19+ is required. Updating it should solve the issue.

**Comment by davappler** [comment]
Thanks a lot, it worked 🚀
