### ISSUE TITLE
Suggestion: Use squash for merging for PRs 

### ISSUE THREAD

**Issue by mattmazzola** [passwordless-id/webauthn#4]
I noticed the recent PRs that I created were merged using the default strategy which results in more complicated git history. 

![image](https://user-images.githubusercontent.com/2856501/200189197-db5b995d-5347-4e8c-8634-b48c9bfe0331.png)

These were very small PRs so it's minor, although I would suggest using the "squash" merge strategy to keep the history of main linear. I wasn't sure if you were aware that you can go to the repo settings and make it the only allowed option so that there isn't a chance to pick the wrong one.

![image](https://user-images.githubusercontent.com/2856501/200189477-c76cdff2-f8fe-450d-8d1f-0b2b611bfbc0.png)

Feel free to close issue or ignore if you'd rather not.

**Comment by dagnelies** [comment]
Hmmm... Ok, let's do that
