### ISSUE TITLE
Does it has commonjs version?

### ISSUE THREAD

**Issue by conanliuhuan** [passwordless-id/webauthn#47]
some old project use commonjs, if upgrade to esm would cost a lot of time. does it has commonjs version?

**Comment by dagnelies** [comment]
See #35

**Comment by dagnelies** [comment]
Basically, I'm not strictly against a commonJS version but I won't do it myself. I consider it to be old legacy that slowly fades away and I such I will not put effort into it. Well tested PR would be accepted though.

**Comment by pranav-growthx** [comment]
I dont see anything in your code that might cause issues with a commonjs build.

I managed to get a commonjs build just by adding a new tsconfig with compilerOptions.module set to commonjs, setting a different outDir and adding an exports block in package.json (and removing type: module in package.json)
