### ISSUE TITLE
Passwordless login with passkeys

### ISSUE THREAD

**Issue by mstaicu** [passwordless-id/webauthn#57]
I'm currently onboarding customers using the `@simplewebauthn` package, but I find the process to be a bit too verbose for my use case.

I wish to give customers the ability to register and login to their accounts only by means of Passkeys. I don't plan on supporting passwords or magic link logins because, in my limited understanding of the protocol, Passkeys should provide the ability to login without any user identifier.

Wanting to know if the `webauthn` package under the `passwordless-id` would let me achieve this. My main friction points with the current implementation is that I need to shuffle around and coordinate registration using `jwt`s and then request the user to imput an identifier such as an email address. I think this is redundant and Passkeys solve this.

Are the examples in the repo demonstrating this functionality, both on the server and on the client?

I guess that I'm trying to ask for a clear example because this is a new paradigm shift, at least in my mind, where we receive the credential from the client side and we have to store those against a user. Subsequently, I assume we can pass during authentication an empty array for credentials and leave the authenticator to discover them (?)

I think this is exactly what I'm trying to achieve https://stackoverflow.com/q/73562080

Thanks and sorry if this was asked before

**Comment by dagnelies** [comment]
I recommend taking a look at the v2 preview https://webauthn-ciy.pages.dev/authentication/ to see the ways to log in.

Basically, while "usernameless" authentication is possible, I would not advise it. If you use credentials "discovery", the user will see passkeys with cryptic names, and if you want to trigger authentication directly using the list of allowed credentials, you still need a way to identify the user and poll the server for the credential IDs.

**Comment by mstaicu** [comment]
Do I have to explicitly "use credential discovery", or that feature is up to the platform / authenticator? My understanding is that after I register the user I create a User in my database and add the credential to his 'devices' array, for example, then in order to authenticate him, I leave the credentials as an empty array on the client side, the authenticator will return a credential, I will send the credential to the server, find a user matching that credential, and the authentication process is complete. Is this a correct understanding?

**Comment by dagnelies** [comment]
That is correct.

Yes, you should keep a list of credentials for the user on the server side.

During authentication, you have two options:

- provide an empty credential IDs list => This will trigger "credential discovery" on the client device and the user can pick any available passkey
- provide the list of allowed credential IDs => The first one also present on the client device will be taken

Note that the exact behavior / UX depends on the platform (and to a lesser extend also the browser).

**Comment by mstaicu** [comment]
Thank you!
