### ISSUE TITLE
Base64 encoding challenge a requirement?

### ISSUE THREAD

**Issue by mcm-ham** [passwordless-id/webauthn#62]
Just trying out this library but got an error from util.parseBase64url with atob saying input is invalid. I see client.register is calling this function, after base64 encoding the challenge i.e. btoa it now works. Is it a requirement that challenge is base64 encoded if so should this be mentioned in the docs or did I miss that somewhere?

**Comment by dagnelies** [comment]
This is actually a tricky one. I remember hesitating to do it, then forgot. 

The main concern is that if you use another lib server side, it expects bytes as challenge. Now, if you encode/decode from string to bytes, the next question is what character encoding to use. So it should state in the fine print that it uses UTF-8 to encode the string into bytes, that is then base64 encoded again in the json payload. Confusing right? In the end, I opted it to be base64 encoded from the start.

 I'll improve the docs

**Comment by mcm-ham** [comment]
That makes sense, thanks for the explanation.

The other thing noted is https://webauthn.passwordless.id/authentication/#3-send-the-payload-to-the-server does not match the new value returned that aligns with JSON version of PublicKeyCredential.

**Comment by dagnelies** [comment]
I'll leave the challenge as base64url. However I leave this ticket open until I improved the docs. I'll also add a `server.createChallenge()` to make things easier/safer.

**Comment by dagnelies** [comment]
There was already `utils.randomChallenge()`. I moved it to `server.randomChallenge()` and documented it.
