### ISSUE TITLE
Minor discrepancy in 'discoverable' option default value of register()

### ISSUE THREAD

**Issue by hjaber** [passwordless-id/webauthn#68]
I want to express my appreciation for your ongoing work on this library. It's been incredibly helpful, and you've been very responsive. I'm sorry to keep bringing up minor issues, I am migrating to V2 and run into things.

I've noticed a small inconsistency between the documentation and the implementation of the 'discoverable' option in the register() function:

- The documentation states the default value is 'preferred'.
- The code doesn't set a default value, which could potentially lead to undefined behavior.

Current implementation in client.ts:
```ts
authenticatorSelection: {
    userVerification: options.userVerification,
    authenticatorAttachment: getAuthAttachment(options.hints),
    residentKey: options.discoverable,
    requireResidentKey: (options.discoverable === 'required')
}
```

Suggestion for alignment (if this matches the intended behavior):
```ts
authenticatorSelection: {
    userVerification: options.userVerification,
    authenticatorAttachment: getAuthAttachment(options.hints),
    residentKey: options.discoverable ?? 'preferred', // add default fallback
    requireResidentKey: (options.discoverable === 'required')
}
```
Alternatively, the documentation could be updated if the current implementation is intentional.

**Comment by hjaber** [comment]
I'm sorry, but just want confirm this because I have different behavior with the passkey ceremony when I set `discoverable: "preferred"` explicitly rather than omitting it and relying on it to default,

[MDN](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredentialCreationOptions#residentkey)

>If omitted, residentKey defaults to "required" if requireResidentKey is true, otherwise the default value is "discouraged".

Based on the implementation, if `discoverable` is omitted, wouldn't it default to `"discouraged"`?

**Comment by dagnelies** [comment]
Reopening for verification
