### ISSUE TITLE
Login hybrid not working

### ISSUE THREAD

**Issue by lil5** [passwordless-id/webauthn#78]
I've tried using the example website to register a passkey but it doesn't work. 

Pc: Windows 11 Chrome
Android: pixel 8

1. Open example website on Pc
2. Click register, enter name
3. Passkey pop-up: select via android with qrcode, displays qrcode
4. Phone: scan qrcode
5. At this point two things happen:
- Phone: endlessly loading 
- Pc: error is thrown (see https://github.com/MasterKale/SimpleWebAuthn/discussions/452 )

**Comment by dagnelies** [comment]
Hmmm... It's hard to tell what's going on. That's a generic error from the underlying protocol. Can you successfully register the same devices using the hybrid flow using some other web demo? Honestly, I have a feeling it's a Windows/Android incompatibility issue in this case. Another interesting experiment would be to register directly with your phone and try the hybrid flow from the pc to see if that works. Lastly, is it the default QR scanner or another QR scanner from the playstore?

**Comment by lil5** [comment]
This was from a co-workers laptop, give me some time to install windows on a laptop and I'll have some more details then. 

The strange thing was that it did work for a different company website (not using passwordless-id).

It wasn't a qrcode issue, default camera app, opened Google Authenticator's passkey native pop-up just fine.

**Comment by dagnelies** [comment]
Closing it as non-reproducible. If you encounter it again some day, just re-open it.
