### ISSUE TITLE
Types are not included in 0.0.12 package

### ISSUE THREAD

**Issue by mattmazzola** [passwordless-id/webauthn#8]
It seems the package was published without the types being generated so the package.types is referencing a non existing locastion

![image](https://user-images.githubusercontent.com/2856501/202954914-9b4cb04c-5dbe-48b5-ac6e-a2868703e5fe.png)

When looking at 0.0.12 package, you can see the `dist/types` is not included 

![image](https://user-images.githubusercontent.com/2856501/202954827-9e51cd09-2ff2-46df-a4da-086fdab127ee.png)

Related to #6 

Also `dist/esm` is not included although that isn't as large of problem, given the minified has same functionality.

**Comment by dagnelies** [comment]
Should now be included
